#!/bin/bash

# test the github distribution in a container

# build the base container

docker build -t torchmoretest-base - <<EOF
FROM ubuntu:22.04
ENV LC_ALL=C
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qqy update
RUN apt-get install -qqy git
RUN apt-get install -qqy python3
RUN apt-get install -qqy python3-pip
RUN apt-get install -qqy python3-venv
RUN apt-get install -qqy curl
WORKDIR /tmp
RUN python3 -m venv venv
RUN . venv/bin/activate; pip3 install --no-cache-dir torch torchvision
RUN . venv/bin/activate; pip3 install --no-cache-dir pytest
RUN . venv/bin/activate; pip3 install --no-cache-dir numpy
RUN . venv/bin/activate; pip3 install --no-cache-dir nbconvert
EOF


case $1 in

local)
(
mkdir -p _docker
cd _docker
cp -av ../torchmore ../tests ../setup.py ../requirements.txt .
cat > Dockerfile <<EOF
FROM torchmoretest-base
ENV SHELL=/bin/bash
COPY . /tmp/torchmore
WORKDIR /tmp/torchmore
RUN ls -l
RUN ln -s /tmp/venv . || true
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF
docker build -t torchmoretest .
)
;;

# run the test as a second stage build without caching

git)
docker build -t torchmoretest --no-cache - <<EOF
FROM torchmoretest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/torchmore.git /tmp/torchmore
WORKDIR /tmp/torchmore
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir -r requirements.txt
RUN . venv/bin/activate; python3 -m pytest
EOF
;;

package)
docker build -t torchmoretest --no-cache - <<EOF
FROM torchmoretest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/torchmore.git /tmp/torchmore
RUN mkdir /tmp/work
RUN cp -av /tmp/torchmore/test* /tmp/work/.
WORKDIR /tmp/work
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
#RUN . venv/bin/activate; pip install --no-cache-dir torchmore
RUN . venv/bin/activate; pip install https://tmb-testreleases.storage.googleapis.com/torchmore-latest-py3-none-any.whl
RUN . venv/bin/activate; python3 -m pytest
EOF
;;

pip)
docker build -t torchmoretest --no-cache - <<EOF
FROM torchmoretest-base
ENV SHELL=/bin/bash
RUN git clone https://git@github.com/tmbdev/torchmore.git /tmp/torchmore
RUN mkdir /tmp/work
RUN cp -av /tmp/torchmore/test* /tmp/work/.
WORKDIR /tmp/work
RUN ln -s /tmp/venv .
RUN . venv/bin/activate; pip install --no-cache-dir pytest
RUN . venv/bin/activate; pip install --no-cache-dir torchmore
#RUN . venv/bin/activate; pip install https://tmb-testreleases.storage.googleapis.com/torchmore-latest-py3-none-any.whl
RUN . venv/bin/activate; python3 -m pytest
EOF
;;

*)
echo $1: must specify either pip or git
exit 1
;;

esac
